# Generated by Django 5.0.7 on 2024-08-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_reaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
